Actomaton/Actomaton

Sources/Actomaton/Actomaton.swift, Sources/ActomatonStore/Store.Proxy.swift, Sources/ActomatonStore/Store.swift, Tests/ActomatonTests/EffectCancellationTests.swift, Tests/ActomatonTests/EffectIDAutoCancellationTests.swift, Tests/ActomatonTests/FeedbackTrackingTaskTests.swift
This PR adds `TaskPriority` & `tracksFeedbacks` features to `Actomaton.send(_ action: Action)`.
```swift
/// Sends `action` to `Actomaton`.
///
/// - Parameters:
///   - priority:
///     Priority of the task. If `nil`, the priority will come from `Task.currentPriority`.
///   - tracksFeedbacks:
///     If `true`, returned `Task` will also track its feedback effects that are triggered by next actions,
///     so that their wait-for-all and cancellations are possible.
///     Default is `false`.
///
/// - Returns:
///   Unified task that can handle (wait for or cancel) all combined effects triggered by `action` in `Reducer`.
@discardableResult
public func send(
_ action: Action,
priority: TaskPriority? = nil,
tracksFeedbacks: Bool = false
) -> Task<(), Never>?
```
=> Add `TaskPriority` & `tracksFeedbacks`

Sources/ActomatonStore/Binding+Helper.swift, Sources/ActomatonStore/OptionalProtocol.swift, Sources/ActomatonStore/Store.Proxy.swift
This PR adds `Store`-transforming functions for more easy creation of child-Stores 
to avoid `Binding`-transform-based approach so that the code from [Actomaton-Gallery](https://github.com/inamiy/Actomaton-Gallery) will drastically improve from:
```swift
extension Example
{
func exampleView<ChildAction, ChildState, V: View>(
store: Store<Root.Action, Root.State>.Proxy,
actionPath: CasePath<Root.Action, ChildAction>,
statePath: CasePath<Root.State.Current, ChildState>,
makeView: (Store<ChildAction, ChildState>.Proxy) -> V
) -> AnyView
{
guard let currentBinding = Binding(store.$state.current),
let stateBinding = Binding(currentBinding[casePath: statePath])
else {
return EmptyView().toAnyView()
}
let substore = Store<ChildAction, ChildState>.Proxy(
state: stateBinding,
send: { …
```
=> [ActomatonStore] Add `Store` transform functions

Sources/ActomatonStore/HostingViewController.swift, Sources/ActomatonStore/RouteStore.swift, Sources/ActomatonStore/Store.swift
This PR adds following features (especially for working with UIKit)
A subclass of `Store` that also emits `route: AnyPublisher<Route, Never>` as output,
which is a common pattern in UIKit-based MVVM that triggers actions outside of its domain.
Note that `RouteStore` has a type of `Reducer<Action, State, SendRouteEnvironment<Environment, Route>>`,
and may additionally need `contramap(environment:)` in case of migrating from SwiftUI-based reducer.
```swift
let store = RouteStore(
state: state,
reducer: reducer, // NOTE: has type of Reducer<Action, State, SendRouteEnvironment<Environment, Route>>
environment: environment,
routeType: Route.self // for quick type-inference
)
```
A wrapper of `UIHostingController` that takes `Store` and `View`'s initializer to be lazily instantiated on …
=> [ActomatonStore] Add `RouteStore` & `HostingViewController` (UIKit support)

Sources/ActomatonStore/Store.Proxy.swift
This PR adds `directStateBinding` to expose internal `Binding<State>` as public
to allow users to perform SwiftUI's plain 2-way binding without sending `Action` and running `Reducer`.
```swift
/// **Direct** state binding which skips sending `Action` and running `Reducer` by directly modifying state,
/// just as plain SwiftUI does 2-way state binding.
///
/// - Note:
///   If you prefer more "strict" Elm-like architecture to always run `Action` & `Reducer`,
///   do not use this method, and use `stateBinding` that converts state-setter to `Action` for indirection instead.
public var directStateBinding: Binding<State>
{
self._state
}
```
=> [ActomatonStore] Add `directStateBinding` to allow making internal `Binding<State>` public

Sources/Actomaton/Actomaton.swift, Sources/Actomaton/Effect.swift, Sources/Actomaton/EffectID.swift, Sources/Actomaton/EffectQueue.swift, Sources/Actomaton/EffectQueuePolicy.swift, Sources/Actomaton/Internal/DebugLog.swift, Tests/ActomatonTests/EffectIDAutoCancellationTests.swift, Tests/ActomatonTests/Fixtures/Fixtures.swift, Tests/ActomatonTests/LoginLogoutTests.swift, Tests/ActomatonTests/RunNewestDiscardOldTests.swift, Tests/ActomatonTests/RunOldestDiscardNewTests.swift, Tests/ActomatonTests/RunOldestSuspendNewTests.swift
This PR refactors `Actomaton` to support **EffectQueue** where the original idea is derived from [Harvest](https://github.com/inamiy/Harvest) and reactive programming (Rx).
In a nutshell, this PR adds **`EffectQueuePolicy` to let multiple effects run sequentially, suspend and run 1 by 1, or discard newest (e.g. preventing chattering actions)**:
```swift
/// `EffectQueueProtocol`'s buffering policy.
public enum EffectQueuePolicy: Hashable
{
/// Runs `maxCount` newest effects, cancelling old running effects.
case runNewest(maxCount: Int)
/// Runs `maxCount` old effects with either suspending or discarding new effects.
case runOldest(maxCount: Int, OverflowPolicy)
public enum OverflowPolicy
{
/// Suspends new effects when `.runOldest` `maxCount` of old effects is reached until one of them is …
```
=> [Actomaton] Support `EffectQueue`

Sources/Actomaton/Actomaton.swift, Tests/ActomatonTests/DeinitTests.swift
This PR fixes running `Task`s retaining `Actomaton` which may cause memory-leak issue
when infinite action feedback loop is taken place (though it's rather rare situation).
This PR fixes by using `[weak self]` inside `Task`'s closure 
so that consecutive effects won't run after `Actomaton` is deinit-ed.
See `DeinitTests` for more info.
This issue exists in [ver 0.1.0](https://github.com/inamiy/Actomaton/releases/tag/0.1.0) and will be fixed by this PR in ver 0.2.0.
=> [Actomaton] Fix running tasks retaining `Actomaton`

Sources/Actomaton/EffectQueue.swift
This PR renames `Oldest1EffectQueueProtocol` (discardNew) with `Oldest1DiscardNewEffectQueueProtocol`,
and also add `Oldest1SuspendNewEffectQueueProtocol` as a new helper.
=> [Actomaton] Add `Oldest1DiscardNewEffectQueueProtocol` & `Oldest1SuspendNewEffectQueueProtocol`

Package.swift
Xcode 13.2 Beta now allows **Swift Concurrency back-deploy** to support macOS 10.15, iOS 13, tvOS 13, and watchOS 6.
So far the functionality works as expected in [Actomaton-Gallery](https://github.com/inamiy/Actomaton-Gallery) 
(tested with iOS 14 simulator, with noticing slow-down than iOS 15 simulator which I haven't elaborated further yet).
See below for more details:
- [Xcode 13.2 Beta Release Notes | Apple Developer Documentation](https://developer.apple.com/documentation/xcode-release-notes/xcode-13_2-release-notes)
=> Use Swift Concurrency back-deploy to support macOS 10.15, iOS 13, tvOS 13, and watchOS 6

Sources/ActomatonStore/Store.Proxy.swift
This PR adds `Store.Proxy.isPresented(onDismiss:)` for easy creation of `Binding<Bool>` (SwiftUI presentation binding) from `Store.Proxy`, which can also send next action on dismissal.
=> [ActomatonStore] Add `Store.Proxy.isPresented(onDismiss:)`

README.md, Sources/Actomaton/Actomaton.swift, Sources/Actomaton/Effect.swift, Sources/ActomatonStore/Store.Proxy.swift, Sources/ActomatonStore/Store.swift, Tests/ActomatonTests/DeinitTests.swift, Tests/ActomatonTests/FeedbackTrackingTaskTests.swift, Tests/ActomatonTests/LoginLogoutTests.swift
This PR refactors Actomaton effect handling by also supporting `async throws` functions.
=> Support `async throws` functions for Effect handling

Sources/ActomatonStore/HostingViewController.swift, Sources/ActomatonStore/Store.ObservableProxy.swift, Sources/ActomatonStore/Store.Proxy.swift, Sources/ActomatonStore/Store.swift
This PR adds **`Store.ObservableProxy` which holds `state: AnyPublisher<State, Never>`** as a derived state from `Store` (single-source-of-truth) that is useful for manual state-diffing (via Combine pipelining) on top of UIKit-based app.
(NOTE: `Store.Proxy` holds `state: Binding<State>` which is for SwiftUI-based app)
Also, `HostingViewController` can now accept not only `Store` but also `Store.ObservableProxy`.
=> [ActomatonStore] Add `Store.ObservableProxy` & improve `HostingViewController`

Sources/ActomatonStore/RouteStore.swift
This PR adds `Reducer.forwardActions` which is convenient to treat `Action` as `Route` and forwarding it directly.
=> [ActomatonStore] Add `Reducer.forwardActions`

Sources/Actomaton/Actomaton.swift, Sources/Actomaton/EffectID.swift
This PR adds internal `DefaultEffectID` to always track running `Task`s so that
Actomaton can cancel them on `deinit`, even when users don't track them manually.
=> [Actomaton] Add internal `DefaultEffectID` to always be able to cancel on `deinit`

Package.resolved, Package.swift, Sources/ActomatonDebugging/Reducer+Debugging.swift
This PR adds a new `ActomatonDebugging` module which uses [CustomDump](https://github.com/pointfreeco/swift-custom-dump) to pretty-print actions and states via `Reducer.debug` .
Also, this PR uses nested enum case pretty-printing technique from:
https://github.com/pointfreeco/swift-composable-architecture/blob/0.33.0/Sources/ComposableArchitecture/Debugging/ReducerInstrumentation.swift
=> Add ActomatonDebugging (using CustomDump)

Sources/ActomatonDebugging/Reducer+Debugging.swift
Successor of:
- #27
This PR enhances #27 by adding state-`diff` format from CustomDump so that gigantic state printing will be narrowed down to only show important diffs.
Also, there are some additions and renaming of #27 's new APIs.
=> [Debugging] Add `StateDebugLogFormat.diff`

Sources/ActomatonStore/ForEach+Store.swift
This PR adds `ForEach.init(store:)` helper methods that allows `Store<Action, [ChildState]>` to traverse by child states in SwiftUI, similar to how original `ForEach` works with `Binding<[ChildState]>`.
```swift
extension ForEach where Content: View
{
/// `ForEach` for `Store` where its state is a collection of child states identified by `id` keyPath.
/// - SeeAlso: Why `zip` is used: https://stackoverflow.com/a/63145650/666371
@MainActor
public init<C, Action>(
store: Store<Action, C>.Proxy,
id: KeyPath<C.Element, ID>,
@ViewBuilder content: @escaping (Store<Action, C.Element>.Proxy) -> Content
) where
Data == [Zip2Sequence<C.Indices, C>.Element],
C: MutableCollection, C: RandomAccessCollection, C.Index: Hashable
{
let firstKeyPath = \Zip2Sequence<C.Indices, C>.Element.1
self.init( …
```
=> [ActomatonStore] Add `ForEach.init(store:)`

Package.swift, Sources/Actomaton/Actomaton.swift, Sources/Actomaton/Effect.swift, Sources/Actomaton/EffectID.swift, Sources/Actomaton/EffectQueue.swift, Sources/Actomaton/EffectQueuePolicy.swift, Sources/Actomaton/Internal/AnyAsyncSequence.swift, Sources/Actomaton/Reducer.swift, Sources/Actomaton/UncheckedSendable.swift, Sources/ActomatonStore/Effect+Combine.swift, Sources/ActomatonStore/ForEach+Store.swift, Sources/ActomatonStore/Store.swift, Sources/ActomatonStore/UIKit-Support/HostingViewController.swift, Sources/ActomatonStore/UIKit-Support/RouteStore.swift, Sources/ActomatonStore/UncheckedSendable.swift, Tests/ActomatonTests/EffectCancellationTests.swift, Tests/ActomatonTests/EffectIDAutoCancellationTests.swift, Tests/ActomatonTests/FeedbackTrackingTaskTests.swift, Tests/ActomatonTests/Fixtures/UncheckedSendable.swift, Tests/ActomatonTests/LoginLogoutTests.swift, Tests/ActomatonTests/RunNewestDiscardOldTests.swift, Tests/ActomatonTests/RunOldestDiscardNewTests.swift, Tests/ActomatonTests/RunOldestSuspendNewTests.swift
This PR adds:
- Swift Concurrency compiler options `-warn-concurrency` and `-enable-actor-data-race-checks` 
as discussed in: [Concurrency in Swift 5 and 6 - Evolution / Discussion - Swift Forums](https://forums.swift.org/t/concurrency-in-swift-5-and-6/49337)
- Conform to `Sendable` / `@Sendable` wherever appropriate
=> Add `Sendable` conformances, `-warn-concurrency` & `-enable-actor-data-race-checks` compiler options

Sources/Actomaton/Actomaton.swift, Sources/Actomaton/Effect.swift, Sources/Actomaton/EffectID.swift, Sources/Actomaton/EffectQueue.swift, Sources/Actomaton/Internal/AnySendableHashable.swift, Sources/Actomaton/UncheckedSendable.swift
This PR adds **`AnySendableHashable` that wraps `AnyHashable` as well as conforming to `@unchecked Sendable`**, as this approach is a better implementation than `extension AnyHashable: @unchecked Sendable` in case of some class-based Hashable might also be type-erased into sendable `AnyHashable` which is potentially dangerous.
See also:
https://twitter.com/inamiy/status/1487671398914936835
=> [Actomaton] Introduce `AnySendableHashable` to avoid `extension AnyHashable: @unchecked Sendable`

Sources/Actomaton/Actomaton.swift, Sources/Actomaton/Effect.swift, Sources/Actomaton/Internal/AnyAsyncSequence.swift, Sources/Actomaton/UncheckedSendable.swift, Sources/ActomatonStore/Effect+Combine.swift, Sources/ActomatonStore/UncheckedSendable.swift, Tests/ActomatonTests/FeedbackTrackingTaskTests.swift, Tests/ActomatonTests/TimerTests.swift
Note: This is a **Breaking Change**.
This PR refactors `AsyncSequence`-based `Effect` by wrapping it with `async` closure so that:
1. Asynchronous work can be done before building `AsyncSequence`
2. Allows adding global actor to async-closure, e.g. `@MainActor`
- This allows easy global-actor-based sequential operation among multiple effect composition (without using `EffectQueue`)
3. `AsyncSequence` will no longer requires conforming to `Sendable`
Previously:
```swift
let effect = Effect(sequence: AsyncStream { continuation in
...
})
```
Now becomes:
```swift
let sequenceEffect = Effect(sequence: { @MainActor in // NOTE: Can attach global actor as a builder actor if needed
// NOTE: Can run more async work before creating AsyncSequence
let someValue = await doSomeWork()
return AsyncStream …
```
=> [Actomaton] Refactor AsyncSequence-based Effect by building it via async closure

Sources/ActomatonStore/ForEach+Store.swift, Sources/ActomatonStore/Store.Proxy.swift, Sources/ActomatonStore/Store.swift, Sources/ActomatonStore/UIKit-Support/HostingViewController.swift, Sources/ActomatonStore/UIKit-Support/RouteStore.swift, Sources/ActomatonStore/UIKit-Support/Store.ObservableProxy.swift
**Breaking Change**.
This PR refactors `ActomatonStore` module to allow **`Store`, `Store.Proxy`, and `Store.ObservableProxy` to hold `environment` as a public property**.
This change is especially needed for `Store` to gracefully interact with other stateful dynamic objects, e.g. `AVPlayer`, due to the following reasons:
1. To put `AVPlayer`  into `Environment` as an external dependency (as usual) to subscribe & unsubscribe its changes inside `Effect` (rather than splitting `AVPlayer` from `Environment`, subscribing inside View, and interacting through public `Action`s)
2. And still be able to pass `Environment`'s `AVPlayer` to `AVKit.VideoPlayer` (passing down to View-level)
In common MVVM architecture, `AVPlayer` normally sits inside ViewModel, performing subscriptions inside, and …
=> [Store] Make `environment` as public property to be able to pass to `SwiftUI.View`

Sources/ActomatonStore/Store.Configuration.swift, Sources/ActomatonStore/Store.Proxy.swift, Sources/ActomatonStore/Store.swift, Sources/ActomatonStore/UIKit-Support/Store.ObservableProxy.swift
Successor of:
- #39 
This PR adds `StoreConfiguration` that owns `updatesStateImmediately` flag to conditionally run Reducer twice (introduced in #39 ) only when such configuration is needed.
=> [Store] Add `StoreConfiguration`

Sources/ActomatonStore/ActomatonStore.docc/Articles/OOP-Tutorial/04-HostingViewController.md, Sources/ActomatonStore/Store.Proxy.swift
(Subtle) **Breaking change**.
This PR removes `Store.Proxy.directStateBinding` since `Store.Proxy.$state` is sufficient.
=> [Store] Replace `Store.Proxy.directStateBinding` with `Store.Proxy.$state`

Sources/Actomaton/Actomaton.swift, Sources/Actomaton/Effect.swift
This PR changes `Effect.init(sequence:)` argument type:
- from `() async throws -> AsyncSequence`
- to `() async throws -> AsyncSequence?`,
making return type Optional only, so this closure is upcast-able from previous one and thus **no breaking change**.
This change allows early `return nil` that is handled equally as `AsyncSequence` that doesn't emit any values.
Because Swift's `AsyncSequence` is more type-strict due to each stream operator (e.g. `map`) having different `AsyncSequence` concrete types, and because mixing those different types are hard to make code right without type-erasing (e.g. sequence with values for normal case and empty sequence for edge case), having this PR's "`nil` as empty sequence" will be more useful.
=> [Actomaton] Make `Effect`'s sequence to return `nil`

Sources/ActomatonStore/UIKit-Support/RouteStore.swift
**No breaking change (additive)**.
This PR adds `SendRouteEnvironment.sendRouteAsync(Stream)` that can send `Route` as well as receiving `Value`(s) from route destination via `async` or `AsyncStream`.
```swift
enum Route: Sendable {
/// `Arg` is for setting up next screen, `Value` is generated from next screen.
case showNextScreen(Arg, completion: (Value) -> Void)
}
...
// Inside `RouteStore`'s Reducer:
Effect {
/// Send `Route` & get `Value` from next screen.
let value = await environment.sendRouteAsync { completion in
return Route.showNextScreen(someArg, completion)
}
return Action.didFinishNextScreen(value)
}
...
store.subscribeRoutes { [weak vc] route in
switch route {
case let .showNextScreen(arg, completion):
let nextVC = NextViewController(arg: arg)
nextVC.onFinished = { [weak vc] …
```
=> [Store] Add `sendRouteAsync(Stream)`

Sources/Actomaton/Actomaton.swift, Tests/ActomatonTests/PendingEffectCancellationTests.swift
This PR fixes cancellation bug when effect is suspended by specific EffectQueue policy e.g. `Oldest1SuspendNewEffectQueueProtocol`.
- As Is:
- After cancellation of either running & suspended effects, suspended effects will become active because they don't get cancelled but only running ones will get cancelled so that there will be enough spaces to run suspended ones.
- To Be:
- Always cancel suspended effects gracefully.
=> [Actomaton] Fix pending effects not being cancelled

Sources/ActomatonStore/Store.Proxy.swift
Improvement for:
- #36 
Due to #36 , `Store.Proxy` now exposes `Environment` as public member variable.
But in many scenarios, only Store-level needs to know about it and can hide its information to `SwiftUI.View`.
In such cases, `Store.Proxy.noEnvironment` can be used to convert `Environment` into `Void`.
=> [Store] Add `Store.Proxy.noEnvironment`

Sources/Actomaton/Actomaton.swift, Tests/ActomatonTests/RunOldestDiscardNewTests.swift
Related: 
- #46 
This PR improves `.runOldest(n, .discardNew)` auto-cancellation handling by force-running idle `effectKind` and cancel immediately.
=> [Actomaton] Fix `.runOldest(n, .discardNew)` auto-cancellation handling

Sources/Actomaton/Actomaton.swift, Sources/Actomaton/EffectQueue.swift, Sources/Actomaton/EffectQueueDelay.swift, Tests/ActomatonTests/EffectQueueDelayTests.swift, Tests/ActomatonTests/Fixtures/Fixtures.swift
**Additive Change**.
This PR introduces **`EffectQueueDelay`** which associates with `EffectQueue` to **automagically adds `Task.sleep` before actually invoking `Effect`s.**
This feature becomes useful when:
- Throttling multiple waiting effects which ensures minimum time interval between effects
- Debouncing and remove old effects by time interval using `EffectQueuePolicy.runNewest(n)`
=> [Actomaton] Add `EffectQueueDelay`

README.md, Sources/Actomaton/Actomaton.docc/Articles/Examples.md, Sources/Actomaton/Actomaton.docc/Articles/Examples/03-Timer.md, Sources/Actomaton/Actomaton.docc/Articles/Examples/04-EffectQueue.md, Sources/Actomaton/Actomaton.docc/Articles/Examples/05-ReducerComposition.md
Documentation for:
- #9 
- #49 
Related:
- #50 
This PR adds documentation for `EffectQueue` and `EffectQueueDelay`.
- [Example 4: EffectQueue | Documentation](https://inamiy.github.io/Actomaton/documentation/actomaton/04-effectqueue)
=> [Docs] Update Actomaton.docc & README.md

Sources/Actomaton/Reducer.swift
This PR adds **`Reducer.map(id:)` & `Reducer.map(queue:)`** just as `Effect` has.
This mappings becomes useful when EffectIDs and EffectQueues are defined differently in multiple modules,
but end user wants to treat them as the same one.
In such scenario:
```swift
// From Module 1
let reducer1 = Reducer { ... } // using EffectQueue1
// From Module2
let reducer2 = Reducer { ... } // using EffectQueue2
// App using Module1 & Module2
let combinedReducer = Reducer.combine(reducer1, reducer2)
.map(queue: { queue in
if queue is EffectQueue1 || queue is EffectQueue2 {
return AppEffectQueue() // unifying into the same EffectQueue
}
return queue
})
```
=> [Actomaton] Add `Reducer.map(id:)` & `Reducer.map(queue:)`

Tests/ActomatonTests/EffectQueueDelayTests.swift
This PR fixes https://twitter.com/inamiy/status/1534013394386558976 
where Xcode 14 Beta 1 (Swift 5.7) fails the async test that was once working in Xcode 13.4 (Swift 5.6),
possibly due to Swift Concurrency change that `Task` cancellation propagation becomes slower than before for some reason.
To alleviate this issue, this PR adds a short delay before `Task.isCancelled` check so that `Task.isCancelled` will be safely observed.
=> [Test] Fix `EffectQueueDelayTests.test_DelayedNewest2EffectQueue` for Swift 5.7 slow cancellation propagation

Tests/ActomatonTests/DeinitTests.swift
Fixes:
- #58 
#58 caused following test failures due to:
1. `deinit` timing is not guaranteed after setting `nil`
2. Order of "effect cancellation" and "deinit checker" is not guaranteed
This PR fixes them by: 1. removing precondition test, 2. using `Set` to ignore event's arrival order.
=> [Test] Fix DeinitTests

Package.swift, Sources/ActomatonStore/Store.swift, Tests/ActomatonStoreTests/DeinitTests.swift, Tests/ActomatonStoreTests/_exported.swift
This PR, Fix tests `ActomatonStore.deinitTests` to pass from failure.
it's ActomatonStore fixed to add `weak self` capture because to when do deinit then not deallocation Store instance.
=> [Store] Fix: Add `func send` task capture `[weak self]`

Sources/ActomatonStore/UIKit-Support/HostingViewController.swift
open classなHostingViewControllerの中でviewDidLoadがpublicで宣言されており、overrideができないためopenに修正
=> fix access level for viewdidload of hostingviewcontroller

Sources/Actomaton/MainActomaton.swift
This PR introduces `@MainActor class MainActomaton` where the original code is derived from `actor Actomaton` for better SwiftUI animation handling.
By adding this new class:
1. Actor-syncing between `MainActor` and `Actomaton` will no longer become necessary
2. #40 will no longer become necessary
The overall codebase will become more simple and developer-friendly.
This PR is not integrated in `ActomatonStore` module yet, which will be done in separate PR.
Also, `ActomatonStore` will be deprecated in future in favor of forth-coming `ActomatonUI` module.
> `MainActomaton.swift` is derived from `Actomaton.swift`
> with replacing to `@MainActor`, fixing unnecessary async-awaits and adding some workarounds.
> 
> **Code must be in sync as much as possible**.
> 
> This code duplication is …
=> Introduce `MainActomaton`

Package.swift, Sources/ActomatonUI/Extensions/Combine+Helper.swift, Sources/ActomatonUI/Extensions/MutableCollection+Helper.swift, Sources/ActomatonUI/Internal/DebugLog.swift, Sources/ActomatonUI/Store/CurrentValuePublisher.swift, Sources/ActomatonUI/Store/Internal/BindableAction.swift, Sources/ActomatonUI/Store/Internal/StoreCore.swift, Sources/ActomatonUI/Store/Store.swift, Sources/ActomatonUI/SwiftUI/Binding+Helper.swift, Sources/ActomatonUI/SwiftUI/ForEach+Store.swift, Sources/ActomatonUI/SwiftUI/ViewStore.swift, Sources/ActomatonUI/SwiftUI/WithViewStore.swift, Sources/ActomatonUI/UIKit/HostingViewController.swift, Sources/ActomatonUI/UIKit/RouteStore.swift, Sources/ActomatonUI/UncheckedSendable.swift, Sources/ActomatonUI/_exported.swift
Successor of:
- #64 
Integration example:
- https://github.com/Actomaton/Actomaton-Gallery/pull/42
This PR adds a new **`ActomatonUI` module** that inherits the core functionality from `ActomatonStore` which also allows SwiftUI-rendering optimization using `ViewStore`.
The original idea of `ViewStore` is from [swift-composable-architecture](https://github.com/pointfreeco/swift-composable-architecture) with compatible API names (e.g. `ViewStore`) and slight internal differences.
Current [Actomaton-Gallery](https://github.com/Actomaton/Actomaton-Gallery/tree/5898d7b96c1d96eeaccce85d615ce83a9aa271dd/Examples/SwiftUI-Gallery) demo app uses `ActomatonStore` as a SwiftUI-bridge of Actomaton.
It has a very simple (and naive) rendering structure: i.e. putting `@StateObject` in a root …
=> Introduce ActomatonUI

Package.swift, Sources/ActomatonUI/Store/Internal/BindableAction.swift, Sources/ActomatonUI/Store/Internal/StoreCore.swift, Sources/ActomatonUI/Store/Store.swift, Sources/ActomatonUI/Store/StoreConfiguration.swift, Sources/ActomatonUI/UIKit/RouteStore.swift, Sources/ActomatonUI/_exported.swift
Continued from:
- #69 
Related:
- #66 
This PR adds `StoreConfiguration` that allows better Action & State debug-logging including the observation of direct-state-binding changes, which wasn't possible before.
By introducing this PR, `ActomatonUI` will now depend on `ActomatonDebugging`.
=> [UI] Add `StoreConfiguration` for Store's better `LogFormat` support

Package.swift, Tests/ActomatonUITests/DeinitTests.swift, Tests/ActomatonUITests/_exported.swift
Related:
- https://github.com/Actomaton/Actomaton/pull/62
- #66 
This PR adds `ActomatonUITests` which is copied from original `ActomatonStoreTests` introduced in https://github.com/Actomaton/Actomaton/pull/62 .
NOTE: The codebase is exactly the same as before.
=> [Test] Add ActomatonUITests

Sources/Actomaton/Actomaton.swift, Sources/Actomaton/MainActomaton.swift
This PR improves effect handling in `Actomaton` and `MainActomaton`, by internally using `Task.detached` so that running-effects don't necessary have to follow the same Actomaton's executor which allows separate execution path from state updates.
=> [Actomaton] Use `Task.detached` for executing effects

Package.swift, Sources/Actomaton/Actomaton.swift, Sources/Actomaton/MainActomaton.swift, Sources/ActomatonStore/Store.swift, Sources/ActomatonUI/Store/Internal/StoreCore.swift
This PR refactors `MainActomaton` by changing it from `public final class` to `package protocol` (thus this PR is a **breaking change**), and move previous implementation into `package class MainActomaton1` (ver 1), then adding a new `MainActomaton2` (ver 2).
`MainActomaton2` is a full replacement of `MainActomaton1` using [Swift 5.9's Custom Executor](https://github.com/apple/swift-evolution/blob/main/proposals/0392-custom-actor-executors.md), which is available from macOS 14.0 / iOS 17.0.
In Swift 5.9, `MainActomaton2` is now capable of inheriting `actor Actomaton`'s existing code without code duplication.
Same as previous ver 1, ver 2 also always runs on top of `MainActor`'s executor by using `Actor.assumeIsolated` method.
`MainActomaton2` is package-internally used in …
=> Use Swift 5.9 custom executor

Package.swift
Retry of:
- #77
This PR updates `Package.swift` by also adding `ActomatonDebugging` as `ActomatonUI` library target.
=> Include `ActomatonDebugging` as `ActomatonUI` library target
